### ISSUE TITLE
requestPasscode 0, registerDevice 0, but login -101

### ISSUE THREAD

**Issue by cuuupid** [storycraft/node-kakao#69] opened 2020-09-20 20:09 UTC
**Describe the bug**
Today the login system stopped working, I tried registering device on a new machine using `client.Auth.requestPasscode(email, password)` and `client.Auth.registerDevice(passcode, email, password, true)` and both were successful (status 0). However when I tried to run `client.login(email, password)` afterwards, it gives me status -101 (ANOTHER_LOGON) which makes no sense on a fresh computer.

**To Reproduce**
Steps to reproduce the behavior.
Ex) 
1. client.Auth.requestPasscode(email, password)
2. client.Auth.registerDevice(passcode, email, password, true)
3. client.login(email, password)

**Expected behavior**
Expected it to login correctly.

**Screenshots**
<img width="218" alt="image" src="https://user-images.githubusercontent.com/6960204/93721084-73c90f00-fb85-11ea-8200-bbaa2f058258.png">
<img width="207" alt="image" src="https://user-images.githubusercontent.com/6960204/93721090-7af01d00-fb85-11ea-9270-4872bea8c9c4.png">
<img width="120" alt="image" src="https://user-images.githubusercontent.com/6960204/93721093-82afc180-fb85-11ea-91a5-8d5b0ea15687.png">

**Comment by storycraft** [comment] 2020-09-21 01:04
This is intended behavior caused by server. You cannot login more than 1 subdevice with same account.
There is option for force login.
```typescript
async login(email: string, password: string, forced: boolean = false);
```
login method at client.ts ApiClient line 57

giving forced value to true will let you login. It will kick other clients unless you don't use TalkApiClient which only provide web apis.

**Comment by storycraft** [comment] 2020-12-10 07:54
Closing too old unconfirmed bug as invalid.

**Closed as completed by storycraft** 2020-12-10 07:54 UTC
Labels: bug
